# Generated by Django 3.2.4 on 2021-06-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('serial_no', models.CharField(default=135452, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.aircraft')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_in', to='airport.airport')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_out', to='airport.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.flight')),
            ],
            options={
                'verbose_name': 'Flight Schedule',
                'verbose_name_plural': 'Flight Schedules',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.IntegerField()),
                ('flight_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.flight', verbose_name='schedule')),
                ('passenger_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.passenger', verbose_name='passenger')),
            ],
        ),
    ]
