# Generated by Django 3.2.4 on 2021-06-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Airport Code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Airport Cities')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
